// https://dbdiagram.io/d/62ccd828cc1bc14cc59b2c95

Table articles as Ref {
  ref_name varchar [
    pk,
    note: 'Manually assigned reference name'
  ]
  ref_id int [
    unique,
    note: 'RefID from HIVDB'
  ]
  doi varchar [
    unique,
    note: 'Digital Object Identifier (DOI)'
  ]
  medline_id int [
    unique,
    note: 'PubMed ID'
  ]
  url varchar [
    unique,
    note: 'Web address of this reference'
  ]
  first_author varchar [
    not null,
    note: 'First author name. Should formed by the surname, a comma and the initial of given names (no dots)'
  ]
  title varchar [not null, note: 'Article title']
  journal_name varchar [ref: > J.journal_name, not null, note: 'Journal name']
  year int [not null, note: 'Publish year']
  published bool [
    not null,
    note: 'If the article is published or not'
  ]
  // date_added date [not null]
  // date_updated date

  Note: 'Table storing core article identifiers that must be maintained manually'
}

Enum continent_enum {
  "Africa"
  "Asia"
  "Europe"
  "North America"
  "Oceania"
  "South America"
}

Table countries as Loc {
  country_code char(3) [
    pk,
    note: 'ISO 3166-1 alpha-3 country code'
  ]
  country_name varchar [
    unique,
    not null,
    note: 'The name of the country or region'
  ]
  continent_name continent_enum [not null]

  indexes {
    continent_name
  }

  Note: 'Constraint table storing country codes, names and their continents'
}

Enum dataset_status_enum {
  "PLOSMED2015"
  "JIntAIDSSoc2020"
  "EX"
  "New"
}

Table datasets as D {
  dataset_name varchar [pk]
  ref_name varchar [ref: > Ref.ref_name]
  continent_name continent_enum
  status dataset_status_enum [not null]
  annotation varchar [note: 'Text annotation for this article']
  action varchar [note: 'Machine readable filter/edit action when summarizing isolates']
  url varchar [unique]

  // latitude float [not null, note: 'Manually maintained latitude of the dataset']
  // longitude float [not null, note: 'Manually maintained longitude of the dataset']

  indexes {
    (ref_name, continent_name) [unique]
  }

  Note: 'Derived dataset (defined as article + contient) table'
}

Table dataset_countries as DLoc {
  dataset_name varchar [ref: > D.dataset_name]
  country_code char(3) [
    ref: > Loc.country_code,
    note: 'ISO 3166-1 alpha-3 country code'
  ]

  indexes {
    (dataset_name, country_code) [pk]
  }

  Note: 'One-to-many table storing country information of datasets; derived from isolate countries'
}

Table journals as J {
  journal_name varchar [
    pk,
    note: 'Name of a journal'
  ]

  Note: 'Constraint table for journals'
}

Enum gene_enum {
  PR
  RT
  IN
}

Enum drug_class_enum {
  PI
  NRTI
  NNRTI
  INSTI
}

Enum amino_acid_enum {
  A [note: 'A/Ala, Alanine']
  C [note: 'C/Cys, Cysteine']
  D [note: 'D/Asp, Aspartic acid']
  E [note: 'E/Glu, Glutamic acid']
  F [note: 'F/Phe, Phenylalanine']
  G [note: 'G/Gly, Glutamine']
  H [note: 'H/His, Histidine']
  I [note: 'I/Ile, Isoleucine']
  K [note: 'K/Lys, Lysine']
  L [note: 'L/Leu, Leucine']
  M [note: 'M/Met, Methionine']
  N [note: 'N/Asn, Asparagine']
  P [note: 'P/Pro, Proline']
  Q [note: 'Q/Gln, Glutamine']
  R [note: 'R/Arg, Arginine']
  S [note: 'S/Ser, Serine']
  T [note: 'T/Thr, Threonine']
  V [note: 'V/Val, Valine']
  W [note: 'W/Trp, Tryptophan']
  Y [note: 'Y/Tyr, Tyrosine']
  X [note: 'Out-frame deletion']
  stop [note: 'Stop codon']
  del [note: 'Deletion']
  ins [note: 'Insertion']
}

Table drug_classes as DClass {
  drug_class drug_class_enum [pk]
  gene gene_enum

  indexes {
    gene
  }
}

Table surv_mutations as SDRM {
  mutation varchar [pk, note: 'Text mutation name']
  gene gene_enum [not null, note: 'Gene']
  drug_class drug_class_enum [not null, note: 'Drug Class']
  position int [not null, note: 'AA Position in gene']
  amino_acid amino_acid_enum [not null, note: 'Mutation amino acid']

  indexes {
    (gene, position, amino_acid) [unique]
  }

  Note: 'Lookup table of surveillance drug resistance mutations (SDRMs)'
}

Enum isolate_source_enum {
  Plasma
  PBMC
  CSF
  Blood
  Panel
  LN
  CVS
  Serum
  Feces
  Rectal
  "Dried Blood Spot"
  Kidney
  FGT
  "FGT-RNA"
  Unknown
}

// Enum isolate_clone_method_enum {
//   None
//   MC
//   NMC
//   Cons
//   BC
//   Unknown
// }

Enum isolate_seq_method_enum {
  Dideoxy
  DNAChip
  NGS
  Unknown
}

Table isolates as Iso {
  dataset_name varchar [ref: > D.dataset_name]
  isolate_name varchar [note: 'Isolate name (PseudoName from HIVDB)']
  patient_id int [not null, note: 'PtID from HIVDB']
  gene gene_enum [not null, note: 'Gene']
  isolate_date date [not null]
  subtype varchar [not null]
  source isolate_source_enum [not null]
  // clone_method isolate_clone_method_enum // looks like all clone_method's are None 
  seq_method isolate_seq_method_enum [not null]
  country_code char(3) [
    ref: > Loc.country_code,
    not null,
    note: 'ISO 3166-1 alpha-3 country code where this isolate was collected'
  ]
  genbank_accn varchar [
    note: 'Genbank accession number(s); comma delimited'
  ]
  cpr_excluded boolean [
    not null,
    note: 'The isolate is excluded by CPR if true'
  ]
  date_entered date [not null]

  indexes {
    (dataset_name, isolate_name, gene) [pk]
    (patient_id, gene, isolate_date) [unique]
    genbank_accn
    country_code
    cpr_excluded
  }

  Note: 'Table storing isolate metadata imported from HIVDB and CPR'

}

Table isolate_mutations as IsoMut {
  dataset_name varchar
  isolate_name varchar [note: 'Isolate name (PseudoName from HIVDB)']
  gene gene_enum [not null, note: 'Gene']
  mutation varchar [not null]
  position int [note: 'AA Position in gene']
  amino_acid amino_acid_enum [note: 'Mutation amino acid']
  is_mixture boolean [note: 'If this position has mixtures']

  indexes {
    (dataset_name, isolate_name, gene, position, amino_acid) [pk]
    (dataset_name, isolate_name, gene, mutation) [unique]
    position
    amino_acid
  }

  Note: 'Table storing isolate mutations imported from CPR'
}

Ref: IsoMut.(dataset_name, isolate_name, gene) > Iso.(dataset_name, isolate_name, gene) 

Table isolate_excluded_surv_mutations as IsoExSDRMs {
  dataset_name varchar
  isolate_name varchar [note: 'Isolate name (PseudoName from HIVDB)']
  gene gene_enum [not null, note: 'Gene']
  mutation varchar [ref: > SDRM.mutation]
  position int [note: 'AA Position in gene']
  amino_acid amino_acid_enum [note: 'Mutation amino acid']

  indexes {
    (dataset_name, isolate_name, gene, position, amino_acid) [pk]
    (dataset_name, isolate_name, gene, mutation) [unique]
    position
    amino_acid
  }

  Note: 'Table storing SDRMs excluded by CPR'
}
Ref: IsoExSDRMs.(dataset_name, isolate_name, gene) > Iso.(dataset_name, isolate_name, gene)

Table patterns as P {
  pattern_id int [pk]
  year int [not null, note: 'Year when this pattern was collected']
  // TODO: we need to clean-up subtypes: for each patient there should be only one subtype
  // subtype varchar [not null]
  country_code char(3) [
    ref: > Loc.country_code,
    not null,
    note: 'ISO 3166-1 alpha-3 country code where this isolate was collected'
  ]

  indexes {
    year
    // subtype
    country_code
  }

  Note: 'Derived pattern table of distinct isolate properties'
}

Table pattern_genes as PGene {
  pattern_id int [ref: > P.pattern_id]
  gene gene_enum

  indexes {
    (pattern_id, gene) [pk]
  }
}

Table pattern_surv_mutations as PMut {
  pattern_id int [ref: > P.pattern_id]
  mutation varchar

  indexes {
    (pattern_id, mutation) [pk]
  }
}

Table dataset_patterns as DP {
  dataset_name varchar [ref: > D.dataset_name]
  pattern_id int [ref: > P.pattern_id]
  num_isolates int [not null, note: 'Number of isolates of this pattern']

  indexes {
    (dataset_name, pattern_id) [pk]
  }
}

Table dataset_summaries as DSum {
  dataset_name varchar [pk, ref: > D.dataset_name]

  isolate_year_begin int [not null, note: 'Isolate year range begin']
  isolate_year_end int [not null, note: 'Isolate year range end']
  isolate_sources varchar [not null, note: 'comma separated distinct isolate sources']
  isolate_seq_methods varchar [not null, note: 'comma separated distinct sequence methods']
  isolate_country_codes varchar [not null, note: 'comma separated distinct country codes']

  num_isolates int [not null, note: 'Number of isolates']
  num_isolates_accepted int [not null, note: 'Number of isolates accepted by CPR']
  num_sdrm_isolates int [not null, note: 'Number of isolates with SDRMs']
  num_sdrm_isolates_accepted int [not null, note: 'Number of isolates with SDRMs accepted by CPR']
  pcnt_sdrm_isolates float [not null, note: 'Percent of isolates with SDRMs']
  pcnt_sdrm_isolates_accepted float [note: 'Percent of isolates with SDRMs accepted by CPR']

  Note: 'Derived dataset (article + contient) summary table'
}

Table dataset_gene_summaries as DGeneSum {
  dataset_name varchar [ref: > D.dataset_name]
  gene gene_enum [note: 'Gene']

  num_isolates int [not null, note: 'Number of isolates']
  num_isolates_accepted int [not null, note: 'Number of isolates accepted by CPR']
  num_sdrm_isolates int [not null, note: 'Number of isolates with SDRMs']
  num_sdrm_isolates_accepted int [not null, note: 'Number of isolates with SDRMs accepted by CPR']
  pcnt_sdrm_isolates float [not null, note: 'Percent of isolates with SDRMs']
  pcnt_sdrm_isolates_accepted float [note: 'Percent of isolates with SDRMs accepted by CPR']

  indexes {
    (dataset_name, gene) [pk]
    gene
  }

  Note: 'Derived dataset summary by gene table'
}

Table dataset_drug_class_summaries as DClassSum {
  dataset_name varchar [ref: > D.dataset_name]
  gene gene_enum [note: 'Gene']
  drug_class drug_class_enum [note: 'Drug class']

  num_isolates int [not null, note: 'Number of isolates with SDRMs']
  num_isolates_accepted int [not null, note: 'Number of isolates with SDRMs accepted by CPR']
  pcnt_isolates float [not null, note: 'Percent of isolates with SDRMs']
  pcnt_isolates_accepted float [note: 'Percent of isolates with SDRMs accepted by CPR']

  indexes {
    (dataset_name, gene, drug_class) [pk]
    gene
    drug_class
  }

  Note: 'Derived dataset summary by drug class table'
}

Table dataset_subtype_summaries as DSubtypeSum {
  dataset_name varchar [ref: > D.dataset_name]
  gene gene_enum
  subtype varchar

  num_isolates int [not null, note: 'Number of isolates']
  num_isolates_accepted int [not null, note: 'Number of isolates accepted by CPR']
  num_sdrm_isolates int [not null, note: 'Number of isolates with SDRMs']
  num_sdrm_isolates_accepted int [not null, note: 'Number of isolates with SDRMs accepted by CPR']
  pcnt_sdrm_isolates float [not null, note: 'Percent of isolates with SDRMs']
  pcnt_sdrm_isolates_accepted float [note: 'Percent of isolates with SDRMs accepted by CPR']

  indexes {
    (dataset_name, gene, subtype) [pk]
    gene
    subtype
  }

  Note: 'Derived dataset summary by subtype table'
}

Table dataset_surv_mutation_summaries as DSDRM {
  dataset_name varchar [ref: > D.dataset_name]
  gene gene_enum
  mutation varchar [ref: > SDRM.mutation]

  num_isolates int [not null, note: 'Number of isolates']
  num_isolates_accepted int [not null, note: 'Number of isolates accepted by CPR']
  pcnt_isolates float [not null, note: 'Percent of isolates with SDRMs']
  pcnt_isolates_accepted float [note: 'Percent of isolates with SDRMs accepted by CPR']

  indexes {
    (dataset_name, gene, mutation) [pk]
    gene
    mutation
  }

  Note: 'Derived table storing the occurrence of SDRMs per articles'
}


Table last_update {
  scope varchar [pk]
  last_update timestamptz [not null]
}
